name: CI - Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up dependencies
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential

    # Build the project
    - name: Build project
      run: make

    # Run tests
    - name: Run tests
      run: make test